Repository DevourTech/snapshotter, pull requests merged in 2021-07, with the labels that each got.

#6 #5 UPD : fixed timestamp to be extracted from latest commit hash
  README.md
  entrypoint.sh
Labels: bug, documentation

#8 Fix git cloning of repo
  .github/workflows/ci.yml
  .gitignore
  Dockerfile
  README.md
  action.yml
  cmd/main.go
  entrypoint.sh
Labels: bug

#10 UPD : added LICENSE
  LICENSE
Labels: documentation
